In [3]:
import numpy as np

In [2]:
# ARITHMETIC OPERATIONS

In [14]:
a1 = np.array([1,2,3,4,5])

In [15]:
a2 = np.array([6,7,8,9,10])

In [16]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [17]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [18]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [19]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [20]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [21]:
a2//a1

array([6, 3, 2, 2, 2])

In [22]:
np.exp(a1),np.log(a1)

(array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ]),
 array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791]))

In [35]:
np.round(np.random.random((3,3))*100,3) #FLOOR ANS CEIL FUNCTION IS ALSO USED

array([[33.859, 52.667, 78.626],
       [21.642, 75.224, 78.513],
       [87.889, 70.737, 85.343]])

In [11]:
# BROADCASTING

In [4]:
arr2 = np.arange(1,26).reshape((5,5))
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr2**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

In [14]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [11]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [12]:
# RELATIONAL
arr2 > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [16]:
# DEEP AND SHALLOW COPY

In [17]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice = a[:5]
slice*10
slice

array([1, 2, 3, 4, 5])

In [19]:
a  #no change in a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
a[4:6]*10

array([50, 60])

In [24]:
b = a   
b[0] = 99   #now a will also change
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
#to avoid the change use copy function
b = a.copy()
b[1] = 100
b

array([ 99, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [27]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
#MATRIX OPERATIONS

In [29]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [30]:
A

array([[1, 2],
       [3, 4]])

In [31]:
B

array([[5, 6],
       [7, 8]])

In [32]:
np.dot(A,B) or #A@B

array([[19, 22],
       [43, 50]])

In [33]:
A.T  #TRANSPOSE

array([[1, 3],
       [2, 4]])

In [34]:
A + B

array([[ 6,  8],
       [10, 12]])

In [35]:
A == B

array([[False, False],
       [False, False]])

In [36]:
np.diag(A)

array([1, 4])

In [37]:
np.trace(A)

np.int64(5)

In [39]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [40]:
np.linalg.matrix_rank(A)

np.int64(2)

In [41]:
#A.T
# A + B
# A * B
# A @ B
# np.dot()
# np.linalg.det()
# np.linalg.inv()
# np.linalg.solve()
# np.linalg.eig()
# np.linalg.matrix_rank()

In [42]:
# ADVANCED ARRAY MANIPULATION

In [43]:
# stacking array

In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [45]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [5]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [6]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [7]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
#SPLITTING ARRAY

In [43]:
A = np.arange(16).reshape(4, 4)
A


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
np.hsplit(A,4)   # 4 MEANS IN HOW MANT PARTS WE WANT TO SPLIT IT

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [45]:
np.vsplit(A,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [46]:
for i in A:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
