In [2]:
 import numpy as np

In [2]:
#NUMPY INDEXING AND SLICING OF VECTORS

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
A = arr[3::2]
A

array([14, 16, 18, 20])

In [7]:
A[3]

np.int64(20)

In [8]:
#NUMPY INDEXING AND SLICING OF MATRICES

In [8]:
arr = np.arange(1,31).reshape((6,5))

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
slice = arr[3:,3:]    #FIRST SLICING WILL SLICE THE ROW AND THE SECOND SLICING WILL SLICE THE COLUMN
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [11]:
a =  arr[:,2]
a
b = arr[::5,::4]  #finding the corner elements 
b

array([[ 1,  5],
       [26, 30]])

In [9]:
# BOOLEAN INDEXING

In [11]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
slice_arr = arr%2 == 0
slice_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [16]:
arr = arr[slice_arr]
arr

array([12, 14, 16, 18, 20])

In [11]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
a3[1,1,1]  #FIRST WILL FETCH THE 2D MATRIX AND LAST 2 IS SAME AS LIKE 2D MATRIX INDEXING

np.int64(13)

In [16]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [17]:
a3[::2,0,::2]   #FETCHING THE CORNER ELEMENTS

array([[ 0,  2],
       [18, 20]])

In [19]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#ITERATING IN A MATRIX

In [22]:
a2 = np.arange(0,12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
for i in np.nditer(a3):  # USING THIS nditer  WE CAN FETCH EACH ELEMENT OF A MATRIX OF ANY DIMENTION
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [30]:
#RESHAPING

In [28]:
np.transpose(a2)
# or
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
a3.ravel()  # IT CONVERTS ANY DIMENTIONN OF ARRAY IN 1-D DIMENTION

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [15]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr[0:2,0:2]   #arr[row start:row end:row end,column start:column end:column step]

array([[1, 2],
       [6, 7]])

In [20]:
arr[2:,1:3]

array([[12, 13],
       [17, 18],
       [22, 23],
       [27, 28]])