In [2]:
import numpy as np

In [3]:
#BASIC ARRAY OPERATION 

In [4]:
arr = np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

IT CONTAINS THE SAME DATA TYPE AND IF ANY ONE IS UNIQUE THEN IT CONVERTS ALL THE DATA IN ONE TYPE

In [5]:
a = [1,2,3,4.5]
a

[1, 2, 3, 4.5]

In [6]:
np.array(a)

array([1. , 2. , 3. , 4.5])

In [7]:
arr = np.array([1.,2.,3., 4])
arr


array([1., 2., 3., 4.])

CONVERTS VECTOR 1D INTO 2D MATRIES

In [8]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#ARRAY GENERATION FUNCTION

In [11]:
arr = np.arange(1,11,2)  #works like range function in python
arr

array([1, 3, 5, 7, 9])

In [12]:
arr = np.zeros((4,8),dtype = int)   # WE CAN GIVE THE DATA TYPE WHICH WE WANT
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
arr = np.ones((7,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.linspace(0,10,5)  # IT WILL CREATE A ARRAY OF 5 NUMBER FROM 0 TO 10 WITH THE SAME GAP BETWEEN THE NUMBERS
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
arr = np.identity(3)   # IT WILL CREATE THE IDENTITY MATRIX
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# RANDOM GENERATION FUNCTON

In [17]:
np.random.rand(10)  # IT WILL GIVE RANDOM TEN NUMS IN NORMALIZARION FORM [0,1]

array([0.62992477, 0.18228528, 0.26349386, 0.36838764, 0.53294523,
       0.03004847, 0.35302434, 0.13932825, 0.41286716, 0.97723268])

In [18]:
np.random.randn(10)  # IT WILL GIVE RANDOM TEN NUMS IN STANDARIZATION FORM [-N,N]

_IncompleteInputError: incomplete input (1974694204.py, line 1)

In [19]:
np.random.randint(10,20,10)  #IT WWILL GENERATE 10 RANDOM INTEGERS FROM 10 TO 19

array([11, 16, 11, 18, 11, 12, 12, 15, 15, 11], dtype=int32)

In [20]:
np.random.random((3,4))

array([[0.09290584, 0.56181756, 0.36534337, 0.18871994],
       [0.27187773, 0.84764241, 0.85634901, 0.94770318],
       [0.62961453, 0.82320911, 0.31204881, 0.99568572]])

In [21]:
a = np.random.randint(1,100,24).reshape(6,4)  #randint(1,100,24) I WANT 24 RANDOM NO. FROM 1 TO 100
a

array([[98, 58, 19, 62],
       [28, 14,  8, 23],
       [12, 89, 36, 15],
       [76, 18, 88, 50],
       [19, 27, 78, 45],
       [66, 12, 40, 93]], dtype=int32)

In [22]:
# ARRAY ATTRIBUTES

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = "int32")
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [15]:
arr.shape  #IT GIVES THE DIMENTIONO OF THE MATRIX LIKE 2X2 

(3, 3)

In [17]:
arr.ndim  # IT GIVES THE DIMENTION OF THE MATRIX LIKE 2D OR 3D

2

In [18]:
arr.size  # IT GIVES THE NO. OF ITEMS IN THE MATRIX

9

In [38]:
arr.dtype

dtype('int64')

In [5]:
arr.itemsize  # IT GIVES THE SIZE OF THE ARRAY WHAT SIZE IT TAKES

4

In [27]:
#CHANGING DATATYPE
arr.astype(np.int32)  #BY DEFAULT IT IS INT64 ITS SIZE(MEMORY) IS 8 BUT FOR INT32 IT IS 4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [21]:
# ARRAY METHODS/FUNCTIONS

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.min()

np.int64(1)

In [37]:
arr.max()

np.int64(9)

In [38]:
arr.sum()  #GIVE SUM OF ALL NUMBERS

np.int64(45)

In [39]:
np.sum(arr,axis = 1)  # it will give the sum of each row  "1 MEANS ROW" WE CAN CHANGE THE FUNCTION MAX,MIN,SUM,PRODUCT

array([ 6, 15, 24])

In [40]:
np.sum(arr,axis = 0)  # it will give the sum of each column "O MEANS COLUMN"

array([12, 15, 18])

In [43]:
np.mean(arr,axis = 0)

array([4., 5., 6.])

In [37]:
arr.std()  #standard deviation

np.float64(2.581988897471611)

In [39]:
arr.argmax()

np.int64(8)

In [40]:
arr.argmin()

np.int64(0)

In [41]:
#RESHAPING AND RESIZING

In [44]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
arr.reshape((5,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [28]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])